[[colors.indexed_colors]]
color = "#6699cc"
index = 68

[[colors.indexed_colors]]
color = "#5fb3b3"
index = 73

[[colors.indexed_colors]]
color = "#99c794"
index = 114

[[colors.indexed_colors]]
color = "#ab7967"
index = 137

[[colors.indexed_colors]]
color = "#a7adba"
index = 145

[[colors.indexed_colors]]
color = "#c594c5"
index = 176

[[colors.indexed_colors]]
color = "#ec5f67"
index = 203

[[colors.indexed_colors]]
color = "#f99157"
index = 209

[[colors.indexed_colors]]
color = "#fac863"
index = 221

[[colors.indexed_colors]]
color = "#1b2b34"
index = 235

[[colors.indexed_colors]]
color = "#343d46"
index = 237

[[colors.indexed_colors]]
color = "#4f5b66"
index = 240

[[colors.indexed_colors]]
color = "#65737e"
index = 243

[[colors.indexed_colors]]
color = "#c0c5ce"
index = 251

[[colors.indexed_colors]]
color = "#cdd3de"
index = 252

[[colors.indexed_colors]]
color = "#d8dee9"
index = 253

[colors.bright]
black = "#65737e"
blue = "#6699cc"
cyan = "#5fb3b3"
green = "#99c794"
magenta = "#c594c5"
red = "#ec5f67"
white = "#ffffff"
yellow = "#fac863"

[colors.normal]
black = "#1b2b34"
blue = "#6699cc"
cyan = "#5fb3b3"
green = "#99c794"
magenta = "#c594c5"
red = "#ec5f67"
white = "#c0c5ce"
yellow = "#fac863"

[colors.primary]
background = "#1b2b34"
foreground = "#c0c5ce"

[font]
size = 10

[font.offset]
y = 2

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Paste"
key = "'"
mods = "Control"

[mouse]
hide_when_typing = true

[window]
decorations = "None"
dynamic_padding = true
padding = { x = 1, y = 1 }
